# Generated by Django 5.0.1 on 2024-09-28 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mainvideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deus_magnus_first_video', models.FileField(upload_to='main_videos/')),
            ],
        ),
        migrations.CreateModel(
            name='BlogDeusMagnus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_deus_magnus_title', models.CharField(blank=True, max_length=255, null=True)),
                ('blog_deus_magnus_description', models.TextField()),
                ('blog_deus_magnus_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('blog_deus_magnus_img', models.ImageField(upload_to='blog_images/')),
                ('blog_deus_magnus_publish_date', models.DateTimeField(auto_now_add=True)),
                ('blog_deus_magnus_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-blog_deus_magnus_publish_date'],
            },
        ),
        migrations.CreateModel(
            name='DeusMagnusEventBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deus_magnus_event_title', models.CharField(blank=True, max_length=255, null=True)),
                ('deus_magnus_event_description', models.TextField()),
                ('deus_magnus_event_sub_title_1', models.CharField(blank=True, max_length=200, null=True)),
                ('deus_magnus_event_description_1', models.TextField()),
                ('deus_magnus_event_sub_title_2', models.CharField(blank=True, max_length=200, null=True)),
                ('deus_magnus_event_description_2', models.TextField()),
                ('deus_magnus_event_sub_title_3', models.CharField(blank=True, max_length=200, null=True)),
                ('deus_magnus_event_description_3', models.TextField()),
                ('deus_magnus_event_sub_title_4', models.CharField(blank=True, max_length=200, null=True)),
                ('deus_magnus_event_description_4', models.TextField()),
                ('deus_magnus_event_sub_title_5', models.CharField(blank=True, max_length=200, null=True)),
                ('deus_magnus_event_description_5', models.TextField()),
                ('deus_magnus_event_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('deus_magnus_event_img', models.ImageField(upload_to='even_images/')),
                ('deus_magnus_event_publish_date', models.DateTimeField(auto_now_add=True)),
                ('deus_magnus_event_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-deus_magnus_event_publish_date'],
            },
        ),
        migrations.CreateModel(
            name='DeusMagnusMainPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deus_magnus_title', models.CharField(blank=True, max_length=255, null=True)),
                ('deus_magnus_description', models.TextField()),
                ('deus_magnus_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('deus_manus_video', models.FileField(upload_to='videos/')),
                ('deus_magnus_publish_date', models.DateTimeField(auto_now_add=True)),
                ('deus_magnus_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-deus_magnus_publish_date'],
            },
        ),
        migrations.CreateModel(
            name='FAQs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FAQs_title', models.CharField(blank=True, max_length=255, null=True)),
                ('FAQs_response', models.TextField()),
                ('FAQs_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('FAQs_publish_date', models.DateTimeField(auto_now_add=True)),
                ('FAQs_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-FAQs_publish_date'],
            },
        ),
        migrations.CreateModel(
            name='GLOSSARY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GLOSSARY_title', models.CharField(blank=True, max_length=255, null=True)),
                ('GLOSSARY_response', models.TextField()),
                ('GLOSSARY_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('GLOSSARY_publish_date', models.DateTimeField(auto_now_add=True)),
                ('GLOSSARY_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-GLOSSARY_publish_date'],
            },
        ),
        migrations.CreateModel(
            name='Guides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guides_title', models.CharField(blank=True, max_length=255, null=True)),
                ('guides_description', models.TextField()),
                ('guides_sub_title_1', models.CharField(blank=True, max_length=200, null=True)),
                ('guides_description_1', models.TextField()),
                ('guides_sub_title_2', models.CharField(blank=True, max_length=200, null=True)),
                ('guides_description_2', models.TextField()),
                ('guides_sub_title_3', models.CharField(blank=True, max_length=200, null=True)),
                ('guides_description_3', models.TextField()),
                ('guides_sub_title_4', models.CharField(blank=True, max_length=200, null=True)),
                ('guides_description_4', models.TextField()),
                ('guides_sub_title_5', models.CharField(blank=True, max_length=200, null=True)),
                ('guides_description_5', models.TextField()),
                ('guides_img', models.ImageField(upload_to='guides_images/')),
                ('guides_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LastDeusMagnusMainPicturePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_deus_magnus_title', models.CharField(blank=True, max_length=255, null=True)),
                ('last_deus_magnus_description', models.TextField()),
                ('last_deus_magnus_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('last_deus_magnus_image', models.ImageField(upload_to='images2/')),
                ('last_deus_magnus_publish_date', models.DateTimeField(auto_now_add=True)),
                ('last_deus_magnus_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_deus_magnus_publish_date'],
            },
        ),
        migrations.CreateModel(
            name='OurManagementsInDeusMagnus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_team_name', models.CharField(blank=True, max_length=255, null=True)),
                ('our_team_position', models.CharField(blank=True, max_length=255, null=True)),
                ('our_team_description', models.TextField()),
                ('our_team_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('our_team_img', models.ImageField(upload_to='our_team_images/')),
                ('our_team_publish_date', models.DateTimeField(auto_now_add=True)),
                ('our_team_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-our_team_publish_date'],
            },
        ),
        migrations.CreateModel(
            name='SecondDeusMagnusMainPicturePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_deus_magnus_title', models.CharField(blank=True, max_length=255, null=True)),
                ('second_deus_magnus_description', models.TextField()),
                ('second_deus_magnus_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('second_deus_magnus_img', models.ImageField(upload_to='images/')),
                ('second_deus_magnus_publish_date', models.DateTimeField(auto_now_add=True)),
                ('second_deus_magnus_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['second_deus_magnus_publish_date'],
            },
        ),
        migrations.CreateModel(
            name='SubPicture_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title_1', models.CharField(blank=True, max_length=200, null=True)),
                ('sub_description_1', models.TextField()),
                ('sub_slug_1', models.SlugField(blank=True, max_length=255, null=True)),
                ('sub_image_1', models.ImageField(upload_to='images_sub/')),
                ('sub_publish_date_1', models.DateTimeField(auto_now_add=True)),
                ('sub_author_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sub_publish_date_1'],
            },
        ),
        migrations.CreateModel(
            name='SubPicture_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title_2', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_description_2', models.TextField()),
                ('sub_slug_2', models.SlugField(blank=True, max_length=255, null=True)),
                ('sub_video_2', models.FileField(upload_to='video_sub/')),
                ('sub_publish_date_2', models.DateTimeField(auto_now_add=True)),
                ('sub_author_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sub_publish_date_2'],
            },
        ),
        migrations.CreateModel(
            name='VideoSubImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_sub_title', models.CharField(blank=True, max_length=200, null=True)),
                ('video_sub_description', models.TextField()),
                ('video_sub_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('video_sub_image', models.ImageField(upload_to='video_sub_images/')),
                ('video_sub_publish_date', models.DateTimeField(auto_now_add=True)),
                ('video_sub_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['video_sub_publish_date'],
            },
        ),
    ]
