# Generated by Django 5.0.1 on 2024-09-28 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deus_magnus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='G',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gub_title_5', models.CharField(blank=True, max_length=200, null=True)),
                ('gescription_5', models.TextField()),
                ('guid_img', models.ImageField(upload_to='guis_images/')),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('guid_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
    ]
