# Generated by Django 5.0.1 on 2024-04-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deus_magnus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deusmagnusmainpost',
            name='deus_magnus_img',
        ),
        migrations.AddField(
            model_name='deusmagnusmainpost',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='deusmagnusmainpost',
            name='video_file',
            field=models.FileField(default=2, upload_to='videos/'),
            preserve_default=False,
        ),
    ]
