# Generated by Django 5.0.1 on 2024-09-28 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deus_magnus', '0002_g'),
    ]

    operations = [
        migrations.DeleteModel(
            name='G',
        ),
    ]
