# Generated by Django 5.0.1 on 2024-04-17 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deus_magnus', '0002_remove_deusmagnusmainpost_deus_magnus_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deusmagnusmainpost',
            old_name='video_file',
            new_name='deus_manus_video',
        ),
    ]
