# Generated by Django 5.0.1 on 2024-09-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deus_magnus', '0003_delete_g'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactvideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deus_magnus_contact_video', models.FileField(upload_to='contact_videos/')),
            ],
        ),
    ]
