# Generated by Django 5.0.1 on 2024-04-17 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deus_magnus', '0003_rename_video_file_deusmagnusmainpost_deus_manus_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deusmagnusmainpost',
            name='thumbnail',
        ),
    ]
