# Generated by Django 5.0.1 on 2024-09-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deus_magnus', '0004_contactvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutvideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deus_magnus_about_video', models.FileField(upload_to='about_videos/')),
            ],
        ),
    ]
