# Generated by Django 5.0.1 on 2024-09-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deus_magnus', '0005_aboutvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FounderPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deus_magnus_founder_p', models.ImageField(upload_to='founder_p/')),
            ],
        ),
    ]
