# Generated by Django 5.0.1 on 2024-04-22 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deus_magnus', '0005_seconddeusmagnusmainpicturepost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LastDeusMagnusMainPicturePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_deus_magnus_title', models.CharField(blank=True, max_length=255, null=True)),
                ('last_deus_magnus_description', models.TextField()),
                ('last_deus_magnus_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('last_deus_magnus_image', models.ImageField(upload_to='images2/')),
                ('last_deus_magnus_publish_date', models.DateTimeField(auto_now_add=True)),
                ('last_deus_magnus_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_deus_magnus_publish_date'],
            },
        ),
    ]
