# Generated by Django 5.0.1 on 2024-04-22 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deus_magnus', '0006_lastdeusmagnusmainpicturepost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_description', models.TextField()),
                ('sub_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('sub_image', models.ImageField(upload_to='images_sub/')),
                ('sub_publish_date', models.DateTimeField(auto_now_add=True)),
                ('sub_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sub_publish_date'],
            },
        ),
    ]
