# Generated by Django 5.0.1 on 2024-10-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deus_magnus', '0007_bashpicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesPagePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deus_magnus_services_p', models.ImageField(upload_to='services_p/')),
            ],
        ),
    ]
