# Generated by Django 5.0.1 on 2024-10-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deus_magnus', '0008_servicespagepicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstatePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deus_magnus_real_estate_p', models.ImageField(upload_to='real_estate_p/')),
            ],
        ),
    ]
