# Generated by Django 5.0.1 on 2024-04-22 15:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deus_magnus', '0008_subpicture_2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubPicture',
            new_name='SubPicture_1',
        ),
        migrations.AlterModelOptions(
            name='subpicture_1',
            options={'ordering': ['sub_publish_date_1']},
        ),
        migrations.RenameField(
            model_name='subpicture_1',
            old_name='sub_author',
            new_name='sub_author_1',
        ),
        migrations.RenameField(
            model_name='subpicture_1',
            old_name='sub_description',
            new_name='sub_description_1',
        ),
        migrations.RenameField(
            model_name='subpicture_1',
            old_name='sub_image',
            new_name='sub_image_1',
        ),
        migrations.RenameField(
            model_name='subpicture_1',
            old_name='sub_publish_date',
            new_name='sub_publish_date_1',
        ),
        migrations.RenameField(
            model_name='subpicture_1',
            old_name='sub_slug',
            new_name='sub_slug_1',
        ),
        migrations.RenameField(
            model_name='subpicture_1',
            old_name='sub_title',
            new_name='sub_title_1',
        ),
    ]
