# Generated by Django 5.0.1 on 2024-04-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deus_magnus', '0009_rename_subpicture_subpicture_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subpicture_2',
            name='sub_image_2',
        ),
        migrations.AddField(
            model_name='subpicture_2',
            name='sub_video',
            field=models.FileField(default=1, upload_to='video_sub/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subpicture_1',
            name='sub_title_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
