# Generated by Django 5.0.1 on 2024-04-24 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deus_magnus', '0010_remove_subpicture_2_sub_image_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subpicture_2',
            old_name='sub_video',
            new_name='sub_video_2',
        ),
    ]
