# Generated by Django 5.0.1 on 2024-10-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deus_magnus', '0010_facilitymanagementpicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deus_magnus_construction_p', models.ImageField(upload_to='construction_p/')),
            ],
        ),
    ]
