# Generated by Django 5.0.1 on 2024-04-25 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deus_magnus', '0011_rename_sub_video_subpicture_2_sub_video_2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_sub_title', models.CharField(blank=True, max_length=200, null=True)),
                ('video_sub_description', models.TextField()),
                ('video_sub_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('video_sub_image', models.ImageField(upload_to='video_sub_images/')),
                ('video_sub_publish_date', models.DateTimeField(auto_now_add=True)),
                ('video_sub_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['video_sub_publish_date'],
            },
        ),
    ]
