# Generated by Django 5.0.1 on 2024-10-05 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deus_magnus', '0012_projectpicture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lastdeusmagnusmainpicturepost',
            name='last_deus_magnus_author',
        ),
        migrations.DeleteModel(
            name='ProjectPicture',
        ),
        migrations.DeleteModel(
            name='LastDeusMagnusMainPicturePost',
        ),
    ]
