# Generated by Django 5.0.1 on 2024-04-25 09:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deus_magnus', '0012_videosub'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VideoSub',
            new_name='VideoSubImage',
        ),
    ]
