# Generated by Django 5.0.1 on 2024-05-02 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deus_magnus', '0013_rename_videosub_videosubimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeusMagnusBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deus_magnus_blog_title', models.CharField(blank=True, max_length=255, null=True)),
                ('deus_magnus_blog_description', models.TextField()),
                ('deus_magnus_blog_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('deus_magnus_blog_img', models.ImageField(upload_to='blog_images/')),
                ('deus_magnus_blog_publish_date', models.DateTimeField(auto_now_add=True)),
                ('deus_magnus_blog_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-deus_magnus_blog_publish_date'],
            },
        ),
    ]
