# Generated by Django 5.0.1 on 2024-05-02 15:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deus_magnus', '0014_deusmagnusblog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeusMagnusBlog',
            new_name='BlogDeusMagnus',
        ),
        migrations.AlterModelOptions(
            name='blogdeusmagnus',
            options={'ordering': ['-blog_deus_magnus_publish_date']},
        ),
        migrations.RenameField(
            model_name='blogdeusmagnus',
            old_name='deus_magnus_blog_author',
            new_name='blog_deus_magnus_author',
        ),
        migrations.RenameField(
            model_name='blogdeusmagnus',
            old_name='deus_magnus_blog_description',
            new_name='blog_deus_magnus_description',
        ),
        migrations.RenameField(
            model_name='blogdeusmagnus',
            old_name='deus_magnus_blog_img',
            new_name='blog_deus_magnus_img',
        ),
        migrations.RenameField(
            model_name='blogdeusmagnus',
            old_name='deus_magnus_blog_publish_date',
            new_name='blog_deus_magnus_publish_date',
        ),
        migrations.RenameField(
            model_name='blogdeusmagnus',
            old_name='deus_magnus_blog_slug',
            new_name='blog_deus_magnus_slug',
        ),
        migrations.RenameField(
            model_name='blogdeusmagnus',
            old_name='deus_magnus_blog_title',
            new_name='blog_deus_magnus_title',
        ),
    ]
