# Generated by Django 5.0.1 on 2024-10-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deus_magnus', '0015_seconddeusmagnusmainpicturepost_second_deus_magnus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deusmagnusmainpost',
            name='deus_magnus_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
