# Generated by Django 5.0.1 on 2024-05-03 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deus_magnus', '0015_rename_deusmagnusblog_blogdeusmagnus_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deusmagnusmainpost',
            options={'ordering': ['deus_magnus_publish_date']},
        ),
    ]
