# Generated by Django 5.1.4 on 2025-01-01 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deus_magnus', '0017_teammemberbirthday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamMemberBirthday',
        ),
    ]
