# Generated by Django 5.0.1 on 2024-05-03 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deus_magnus', '0017_alter_deusmagnusmainpost_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deusmagnusmainpost',
            name='thumbnail',
        ),
    ]
