# Generated by Django 5.0.1 on 2024-05-06 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deus_magnus', '0018_remove_deusmagnusmainpost_thumbnail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardOfDirectorsInDeusMagnus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_of_directos_name', models.CharField(blank=True, max_length=255, null=True)),
                ('board_of_directos_position', models.CharField(blank=True, max_length=255, null=True)),
                ('board_of_directos_description', models.TextField()),
                ('board_of_directos_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('board_of_directos_img', models.ImageField(upload_to='directors_images/')),
                ('board_of_directos_publish_date', models.DateTimeField(auto_now_add=True)),
                ('board_of_directos_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-board_of_directos_publish_date'],
            },
        ),
    ]
