# Generated by Django 5.0.1 on 2024-05-09 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deus_magnus', '0019_boardofdirectorsindeusmagnus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OurManagementsInDeusMagnus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_team_name', models.CharField(blank=True, max_length=255, null=True)),
                ('our_team_position', models.CharField(blank=True, max_length=255, null=True)),
                ('our_team_description', models.TextField()),
                ('our_team_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('our_team_img', models.ImageField(upload_to='our_team_images/')),
                ('our_team_publish_date', models.DateTimeField(auto_now_add=True)),
                ('our_team_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-our_team_publish_date'],
            },
        ),
    ]
