# Generated by Django 5.1.5 on 2025-01-24 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deus_magnus', '0019_subpicture_1_sub_image_2_subpicture_1_sub_image_3'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subpicture_1',
            options={'ordering': ['-sub_publish_date_1']},
        ),
    ]
