# Generated by Django 5.1.5 on 2025-01-24 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deus_magnus', '0020_alter_subpicture_1_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subpicture_1',
            name='sub_image_2',
        ),
        migrations.RemoveField(
            model_name='subpicture_1',
            name='sub_image_3',
        ),
    ]
