# Generated by Django 5.0.1 on 2024-08-07 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deus_magnus', '0021_deusmagnuseventblog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FAQs_title', models.CharField(blank=True, max_length=255, null=True)),
                ('FAQs_response', models.TextField()),
                ('FAQs_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('FAQs_publish_date', models.DateTimeField(auto_now_add=True)),
                ('FAQs_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-FAQs_publish_date'],
            },
        ),
    ]
