# Generated by Django 5.1.5 on 2025-01-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deus_magnus', '0021_remove_subpicture_1_sub_image_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoomPump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deus_magnus_boom_p', models.ImageField(upload_to='boom_p/')),
            ],
        ),
        migrations.CreateModel(
            name='ConcreteSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deus_magnus_concrete_p', models.ImageField(upload_to='concrete_p/')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentHire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deus_magnus_equipment_p', models.ImageField(upload_to='equipment_p/')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deus_magnus_material_p', models.ImageField(upload_to='material_p/')),
            ],
        ),
        migrations.CreateModel(
            name='SpecializedServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deus_magnus_specialized_p', models.ImageField(upload_to='specialized_p/')),
            ],
        ),
    ]
