# Generated by Django 5.0.1 on 2024-08-08 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deus_magnus', '0022_faqs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GLOSSARY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GLOSSARY_title', models.CharField(blank=True, max_length=255, null=True)),
                ('GLOSSARY_response', models.TextField()),
                ('GLOSSARY_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('GLOSSARY_publish_date', models.DateTimeField(auto_now_add=True)),
                ('GLOSSARY_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-GLOSSARY_publish_date'],
            },
        ),
    ]
