# Generated by Django 5.0.1 on 2024-08-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deus_magnus', '0023_glossary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mainvideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deus_magnus_first_video', models.FileField(upload_to='main_videos/')),
            ],
        ),
    ]
