# Generated by Django 5.0.1 on 2024-08-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deus_magnus', '0024_mainvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_title', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
