# Generated by Django 5.0.1 on 2024-08-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deus_magnus', '0025_footerpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerpost',
            name='copyright_year',
            field=models.PositiveIntegerField(default=2024),
        ),
    ]
