# Generated by Django 5.0.1 on 2024-09-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deus_magnus', '0026_footerpost_copyright_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='deusmagnuseventblog',
            name='deus_magnus_event_description_1',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deusmagnuseventblog',
            name='deus_magnus_event_description_2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deusmagnuseventblog',
            name='deus_magnus_event_description_3',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deusmagnuseventblog',
            name='deus_magnus_event_description_4',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deusmagnuseventblog',
            name='deus_magnus_event_description_5',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deusmagnuseventblog',
            name='deus_magnus_event_sub_title_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='deusmagnuseventblog',
            name='deus_magnus_event_sub_title_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='deusmagnuseventblog',
            name='deus_magnus_event_sub_title_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='deusmagnuseventblog',
            name='deus_magnus_event_sub_title_4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='deusmagnuseventblog',
            name='deus_magnus_event_sub_title_5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='footerpost',
            name='copyright_year',
            field=models.PositiveIntegerField(default=2025),
        ),
    ]
