# Generated by Django 5.0.1 on 2024-09-23 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deus_magnus', '0027_deusmagnuseventblog_deus_magnus_event_description_1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guides_title', models.CharField(max_length=255)),
                ('guides_introduction', models.TextField()),
                ('guides_key_factors', models.JSONField()),
                ('guides_investment_benefits', models.JSONField()),
                ('guides_steps_to_navigate', models.JSONField()),
                ('guides_conclusion', models.TextField()),
                ('guides_img', models.ImageField(upload_to='guides_images/')),
                ('guides_publish_date', models.DateTimeField(auto_now_add=True)),
                ('guides_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-guides_publish_date'],
            },
        ),
    ]
