# Generated by Django 5.0.1 on 2024-09-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deus_magnus', '0028_guide'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guide',
            old_name='guides_introduction',
            new_name='guides_introduction_description',
        ),
        migrations.AddField(
            model_name='guide',
            name='guides_slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
