# Generated by Django 5.0.1 on 2024-09-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deus_magnus', '0029_rename_guides_introduction_guide_guides_introduction_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guide',
            old_name='guides_conclusion',
            new_name='guides_description',
        ),
        migrations.RenameField(
            model_name='guide',
            old_name='guides_introduction_description',
            new_name='guides_description_1',
        ),
        migrations.RemoveField(
            model_name='guide',
            name='guides_investment_benefits',
        ),
        migrations.RemoveField(
            model_name='guide',
            name='guides_key_factors',
        ),
        migrations.RemoveField(
            model_name='guide',
            name='guides_slug',
        ),
        migrations.RemoveField(
            model_name='guide',
            name='guides_steps_to_navigate',
        ),
        migrations.AddField(
            model_name='guide',
            name='guides_description_2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guide',
            name='guides_description_3',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guide',
            name='guides_description_4',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guide',
            name='guides_description_5',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guide',
            name='guides_sub_title_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='guide',
            name='guides_sub_title_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='guide',
            name='guides_sub_title_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='guide',
            name='guides_sub_title_4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='guide',
            name='guides_sub_title_5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='guides_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
