# Generated by Django 5.0.1 on 2024-09-25 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deus_magnus', '0030_rename_guides_conclusion_guide_guides_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guide',
            options={},
        ),
        migrations.RemoveField(
            model_name='guide',
            name='guides_publish_date',
        ),
    ]
