# Generated by Django 5.0.1 on 2024-09-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deus_magnus', '0031_alter_guide_options_remove_guide_guides_publish_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guide',
            options={'ordering': ['-guides_publish_date']},
        ),
        migrations.AddField(
            model_name='guide',
            name='guides_publish_date',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
