# Generated by Django 5.0.1 on 2024-09-27 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deus_magnus', '0032_alter_guide_options_guide_guides_publish_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FooterPost',
        ),
    ]
