# Generated by Django 5.0.1 on 2024-09-27 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deus_magnus', '0033_delete_footerpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guide',
            options={'ordering': ['-guides_publish_date'], 'verbose_name': 'Guide', 'verbose_name_plural': 'Guides'},
        ),
    ]
