# Generated by Django 5.0.1 on 2024-09-27 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deus_magnus', '0034_alter_guide_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guide',
            options={'ordering': ['-guides_publish_date']},
        ),
    ]
