# Generated by Django 5.0.1 on 2024-09-27 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deus_magnus', '0035_alter_guide_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guide',
            options={},
        ),
        migrations.RemoveField(
            model_name='guide',
            name='guides_publish_date',
        ),
    ]
